### ISSUE TITLE
How to (properly) vectorize the forward function

### ISSUE THREAD

**Issue by TheVincentWagner** [Systems-Theory-in-Systems-Biology/EPI#103]
@kaiserls raised a good point in one of his recent reviews concerning the vectorized forward pass:

I think the problem was that for some models a 1-d array is a single parameter and for some, a 1-d array is a list of parameters. I see several options:

    * Make another function: forward_vectorized(...)
    * Make another parameter: multiple_parameters:bool
    * Try to use the model param dim to understand whether multiple evaluations are needed
    * "Force" the user to avoid scalars. then a 1d-array is always one param, and a 2d-array is always multiple params. I am actually not sure how our sampler emcee is using the forward function and how this would work.
    * Is there another, better option? I am not really a fan of any of my options at the moment

From the proposed solutions, I prefer forward_vectorized. 
However, I find it even more elegant to overload the forward pass.
In principle, we should have the information about the parameter dimension of the model, shouldn't we? 

Or didn't I get your point?

**Comment by castellinilinguini** [comment]
I believe this was already fully implemented in #142 , right?

**Comment by kaiserls** [comment]
Yes, the forward function is vectorized in #142. A similiar issue could arise for the jacobian and the forward_and_jacobian method, if we want to vectorize our algorithm at some point. I think we can close the issue for now and create a new one, when needed.

**Comment by castellinilinguini** [comment]
Alright, I'll close it for now!
