### ISSUE TITLE
Documentation is ahead of current eulerpi version in pypi

### ISSUE THREAD

**Issue by shoepfl** [Systems-Theory-in-Systems-Biology/EPI#145]
The EPI documentation includes an Example of DataPCA:

`data_transformation = DataPCA(data, n_components=model.param_dim)  # perform PCA on the data before inference`

However, the class "DataPCA" does not take ` n_components` as argument, rather the `from_data` method of this class takes the argument.

We should think if it makes sense to include `n_components` already in the init function or change the docs accordingly.

**Comment by shoepfl** [comment]
Nevermind the data_transformation does not work at all as it is described in the docs - We probably have to reexamine the whole thing

**Comment by shoepfl** [comment]
The problems described occurred because the docs currently describe the main branch of this repo—which is fine—but the latest eulerpi version on PyPI is behind this version of main, which is not good.

**Comment by castellinilinguini** [comment]
Should have been fixed with the latest release.
