### ISSUE TITLE
Get results directly from inference method

### ISSUE THREAD

**Issue by kaiserls** [Systems-Theory-in-Systems-Biology/EPI#15]
Hey together,

I have a request to improve the workflow with epi:

**Is your feature request related to a problem? Please describe.**
I want to have access to the results as numpy array directy after running 'inference` without dealing with the path structure.

**Describe the solution you'd like**
I'd like `inference` to return the parameters, densities and simulation results or the result manager, which can give me these variables

**Describe alternatives you've considered**
See the two options above.

**Comment by castellinilinguini** [comment]
@kaiserls This feature should be added through #22 .
