### ISSUE TITLE
Default result manager neglects all runs but the first when burning mcmc samples

### ISSUE THREAD

**Issue by castellinilinguini** [Systems-Theory-in-Systems-Biology/EPI#23]
**Describe the bug**
When using the load_sim_results function of the default results manager with a user-specified burn-in period, only the samples of the first run are actually burned.

**To Reproduce**
```python
import numpy as np
import matplotlib.pyplot as plt

from epi.core.inference import inference, InferenceType
from epi.examples.temperature import TemperatureArtificial

# define the model
temperature_model = TemperatureArtificial()

# generate artificial data
temperature_params = temperature_model.generate_artificial_params(1000)
temperature_data = temperature_model.generate_artificial_data(temperature_params)
temperature_slices = [np.array([0])]

# MCMC inference
temperature_mcmc_num_samples = 200
temperature_mcmc_overall_params, temperature_mcmc_sim_results, temperature_mcmc_density_evals, temperature_mcmc_results_manager = inference(
    model = temperature_model,
    data = temperature_data,
    inference_type = InferenceType.MCMC,
    num_steps = temperature_mcmc_num_samples,
    num_walkers = 100,
    num_runs = 1,
    slices = temperature_slices,
    run_name = "burn_in_bug_reproduction",
)

loaded_density_evals, loaded_sim_results, loaded_param_chain = temperature_mcmc_results_manager.load_sim_results(slice = np.array([0]), 
                                                  num_burn_samples = 50,
                                                  occurrence = 1,
                                                  )
print("Number of loaded samples is " + str(loaded_param_chain.shape[0]) + " but should be 15000")
plt.hist(loaded_param_chain, bins = 20, density=True, alpha = 0.5, label = "MCMC sample")
plt.hist(temperature_params, bins = 20, density=True, alpha = 0.5, label = "True parameter")
plt.legend()
plt.show()
```

**Expected behavior**
The first num_burn_samples of all runs are not in the obtained arrays.

**Observed behavior**
Only the fist num_burn_samples of the first run are not in the obtained arrays.

**Screenshots**
![image](https://user-images.githubusercontent.com/63878559/230084933-80067714-9b25-4938-8656-8507c006c525.png)
The screenshot shows a clear bias towards the distribution of the initial walker positions.

**Additional context**
OS: Ubuntu 22.04 LTS

**Comment by kaiserls** [comment]
Why would you expect this to happen? The run is basically just a save point and two consecutive runs should be equivalent to one run with the total number of steps.

**Comment by castellinilinguini** [comment]
Ah, I see, I think I misunderstood the meaning of some parameters. Since I'll be updating the method shortly, I'm also going to make this a bit clearer in the documentation.
