### ISSUE TITLE
Numburn samples has no sensible default / no documentation for recommended values

### ISSUE THREAD

**Issue by kaiserls** [Systems-Theory-in-Systems-Biology/EPI#24]
**Describe the bug**
MCMC with a even number of walkers and and e.g. occurence=2 ignores half of the walkers.

Inspect load_sim_results for correct implementation (order of loaded samples etc.)
also for loading dense grid results
...

**Comment by TheVincentWagner** [comment]
We should at the same time clearly indicate how the runs, walkers and steps are precisely concatenated.

**Comment by castellinilinguini** [comment]
Does #46 solve that issue for you? Now inference defaults to burning 10% of the samples and no thinning. I would argue that independence of subsequent samples in the parameter chain isn't very important for most of the users (or at least less important than having higher accuracy in the parameter density estimate), so I set the default to no thinning. Is there consensus on that or should we discuss this further?

**Comment by castellinilinguini** [comment]
> **Describe the bug** MCMC with a even number of walkers and and e.g. occurence=2 ignores half of the walkers.

I think we should also change the behavior of num_burn_in_samples: Right now, this is the total number of samples (the sum over all chains). I think num_burn_in_samples should be the number of burned samples per chain instead.

**Comment by castellinilinguini** [comment]
Turns out the last fix also undid the changes made before, I'll have to look into this again.
