### ISSUE TITLE
Dense grid evaluation does not work for SBML model

### ISSUE THREAD

**Issue by TheVincentWagner** [Systems-Theory-in-Systems-Biology/EPI#28]
When using the Menten SBML model, a dense grid inference returns a "cannot pickle 'SwigPyObject' object" error.

While 
`model = MentenSBMLModel()

num_data_points = 10
true_param_sample = model.generate_artificial_params(num_data_points)
true_data_sample = model.generate_artificial_data(true_param_sample)

inference(model,
          data = true_data_sample, 
          inference_type=InferenceType.MCMC, 
          slices = [np.array([0])], 
          run_name = "run_mini_sample")`

works perfectly fine, 

`model = MentenSBMLModel()

num_data_points = 10
true_param_sample = model.generate_artificial_params(num_data_points)
true_data_sample = model.generate_artificial_data(true_param_sample)

inference(model,
          data = true_data_sample, 
          inference_type=InferenceType.DENSE_GRID, 
          slices = [np.array([0])], 
          run_name = "run_mini_grid")`

returns an error.
Ideally, they would both perform a parameter inference, but only sampling works.
This issue seems to be independent from other issues concerning sbml models like the data dimension for example.

**Comment by kaiserls** [comment]
Planned changes in EPI to fix #36 will likely reintroduce this issue
