### ISSUE TITLE
Temperature model does not use artificially created data

### ISSUE THREAD

**Issue by TheVincentWagner** [Systems-Theory-in-Systems-Biology/EPI#29]
The generate artificial data method of the temperature model is overwritten so that it never actually generates artificial data but just loads the true temperature data from a csv-file.

**Comment by kaiserls** [comment]
> The generate artificial data method of the temperature model is overwritten so that it never actually generates artificial data but just loads the true temperature data from a csv-file.

I don't see that the temperature model is overwriting `generate_artificial_data` method. The `generate_artificial_params` is indeed returning params from a csv file.
