### ISSUE TITLE
Improve dependency management

### ISSUE THREAD

**Issue by kaiserls** [Systems-Theory-in-Systems-Biology/EPI#30]
**Is your feature request related to a problem? Please describe.**
Epipy users are forced to install the sbml and the amici library and the corresponding c++ libraries even if they do not need sbml support. This complicates the installation process.

**Describe the solution you'd like**
Make amici an optional dependency for epipy. The installation would/should look like this
`pip install epipy` or `pip install epipy[sbml]` depending on whether sbml support is wanted.
Additionally we could build wheels which include the cpp dependencies: https://davidmontague.xyz/posts/packaging-native-extensions-with-poetry/

**Describe alternatives you've considered**
-

**Additional context**
Are all c++ dependencies for epipy already specified in the installation instructions?

**Comment by TheVincentWagner** [comment]
@shoepfl this refers to the [discussion](https://github.com/orgs/Systems-Theory-in-Systems-Biology/discussions/37) you started, doesn't it?

**Comment by shoepfl** [comment]
yes exactly, there are also some tips for the amici installation and I like the solution to install the amici dependency optional

**Comment by TheVincentWagner** [comment]
I tried to use eulerpi without installing amici but the model class currently depends on amici. 
Therfore, you can currently not effectively infer parameters with eulerpi without previously installing amici.

**Comment by TheVincentWagner** [comment]
Sorry, I accidentally closed this issue.
