### ISSUE TITLE
Inference for linear ODE model stops working if data sample size is larger than 2^16  = 65536 data points

### ISSUE THREAD

**Issue by castellinilinguini** [Systems-Theory-in-Systems-Biology/EPI#36]
**Describe the bug**
If the data sample is larger than 2^16  = 65536 data points for the linear ODE model, both MCMC inference as well as dense grid inference stop working. Calling inference with the corresponding parameters results in the call not returning while the CPU is almost on idle.

**To Reproduce**

```python
import numpy as np
from eulerpi.examples.simple_models import LinearODE
from eulerpi.core.inference import inference, InferenceType

# define the model
linear_ode_model = LinearODE()

# generate artificial data
linear_ode_params = linear_ode_model.generate_artificial_params(65536)
linear_ode_data = linear_ode_model.generate_artificial_data(linear_ode_params)

# run EPI with the trivial slices
linear_ode_num_grid_points = 50
linear_ode_slices = [np.array([0]), np.array([1])]
# dense grid inference
linear_ode_dense_grid_overall_params, linear_ode_dense_grid_sim_results, linear_ode_dense_grid_density_evals, linear_ode_dense_grid_results_manager = inference(
    model = linear_ode_model,
    data = linear_ode_data,
    inference_type = InferenceType.DENSE_GRID,
    num_grid_points = linear_ode_num_grid_points,
    slices = linear_ode_slices,
    run_name = "dense_grid_bug_reproduction",
)

# MCMC inference
linear_ode_mcmc_overall_params, linear_ode_mcmc_sim_results, linear_ode_mcmc_density_evals, linear_ode_mcmc_results_manager = inference(
    model = linear_ode_model,
    data = linear_ode_data,
    inference_type = InferenceType.MCMC,
    num_steps = 1000,
    slices = linear_ode_slices,
    run_name = "MCMC_bug_reproduction",
)

```
**Expected behavior**
Both dense grid and MCMC inference produce results within finite time running.

**Observed behavior**
The function calls to inference never return, while cpu is almost on idle.

**Additional context**
OS Ubuntu 22.04.02 LTS
Processor Intel® Core™ i7-7500U CPU @ 2.70GHz × 4
8 GB RAM

**Comment by castellinilinguini** [comment]
@kaiserls Would you mind trying if this bug occurs on your machine too?

**Comment by kaiserls** [comment]
I can confirm this bug. The evaluate_density function never returns.

**Comment by castellinilinguini** [comment]
@kaiserls Unfortunately, tt seems like just switching back from jnp to np in eval_kde_gauss doesn't solve the issue. The code runs until reaching the line `pool.map(work, range(num_processes)` -  after that, CPU is on idle while the call doesn't return.

```python

def test_KDE_multiprocessing(num_datapoints=100_000, num_processes=4):
    """Test whether the KDE works with multiprocessing"""
    
    data = np.random.randn(num_datapoints, 2)
    stdevs = calc_kernel_width(data)
    evalPoint = np.array([0.5, 0.5])
    
    global work
    def work(process_id):
        print(process_id)
        evaluated = eval_kde_gauss(data, evalPoint, stdevs)
        assert evaluated.shape == ()

    pool = MultiPool(num_processes)
    pool.map(work, range(num_processes))
    pool.close()
    pool.join()

    assert True
```

**Comment by kaiserls** [comment]
Are you sure that you replaced all occurences of jnp functions and objects with their numpy / scipy equivalents? The typing does not matter. Therefore replace
- jnp.newaxis
- jnp.scipy.stats norm
- jnp.prod
- jnp sum
On my computer the test is passing then.

This however makes the issue in general only worse. With these changes the test_dense_grid is not terminating for data_sizes ~ 10_000. We could replace all of the calculations with jnp besides the actual derivative calculation with numpy. Then we would only need to take care of the "interface" between jnp and np.

I would argue that the root cause should be tackled, however I have no idea how to fix it. The solution of changing the start method for the processes in https://github.com/google/jax/issues/1805 did not work for me

**Comment by kaiserls** [comment]
The best way to solve this issue to change the spawn method and to make our Model classes pickable.

```
"""Test pickling of the various classes in the package."""

import dill as pickle
import pytest

def test_pickle_SBML():
    from eulerpi.examples.sbml.sbml_caffeine_model import CaffeineSBMLModel
    model = CaffeineSBMLModel(skip_creation=True)
    dumped = pickle.dumps(model)
    loaded = pickle.loads(dumped)
    assert model == loaded
```

```
class SBMLModel(Model):
    ....

    # Allow the model to be pickled
    def __getstate__(self):
        # Create a copy of the object's state
        state = self.__dict__.copy()
        # Remove the unpicklable entries.
        del state["model"]
        del state["solver"]
        return state
    
    # Allow the model to be unpickled and restore the state
    def __setstate__(self, state):
        # TODO: Obviously this implementation is not sufficient, as model and solver are not saved into the state by pickle
        self.__dict__.update(state)
```
