### ISSUE TITLE
Scale all data to have mean 0 and variance 1 to improve numerical stability for high data dimensionality

### ISSUE THREAD

**Issue by castellinilinguini** [Systems-Theory-in-Systems-Biology/EPI#38]
**Is your feature request related to a problem? Please describe.**
Right now, EPI doesn't work properly for the stock example if the distributions are too wide. This seems to stem from an numerical issue, where the variances of the data dimensions differ by multiple orders of magnitude, leading to rounding errors stacking up to wrong results. The large support of the pdfs in the data space also leads to extremely small densities, adding to the numerical problems.

**Describe the solution you'd like**
A possible fix, as suggested by @VivianeKlingel for this problem would be to scale all data dimensions to have mean zero and variance one. This transformation wouldn't affect much of the computational base, as it only adds a constant factor to the parameter distribution (see below). However, some additional discussion between the main contributors is required where exactly the transformation should be applied (@TheVincentWagner , @kaiserls ). 

![image](https://user-images.githubusercontent.com/63878559/231768967-b5090105-0890-4d72-857c-95fc6da53aab.png)

**Describe alternatives you've considered**
The alternative of just scaling the data distribution by a constant factor does not seem promising as it doesn't address the issue of large differences of variance in the data space. 

**Additional context**
Estimation results often look like this:

![image](https://user-images.githubusercontent.com/63878559/231774856-bf13a429-7a92-4e61-954b-fae991f20de4.png)

**Comment by castellinilinguini** [comment]
Actually, I'm tending towards using a transformation that also makes the different dimensions uncorrelated (scaling with $L^{-1}$ where $L \bar{L^T} = \Sigma$ as obtained from a cholesky decomposion of the covariance matrix $\Sigma$), as uncorrelated dimensions should benefit the KDE too. Also, this barely adds computational overhead. Opinions on this?

**Comment by TheVincentWagner** [comment]
I like this Idea very much. Our results from the whiteboard screenshot should still be valid if I see this correctly?

**Comment by castellinilinguini** [comment]
Yes, the result should still be valid. However, I notice we missed one transformation, the last line should read
$\Phi_Q(q) = \Phi_Y(T s(q)) \cdot \det M \cdot \det Js$
