### ISSUE TITLE
model(param) is unequal to model.forward(param)

### ISSUE THREAD

**Issue by TheVincentWagner** [Systems-Theory-in-Systems-Biology/EPI#99]
**Describe the bug**
In the model class documentation it states that the forward model evaluation can either be performed by 
model.forward(param) or
model(param). 
However, the two results do not agree.

**To Reproduce**
```python
import numpy as np
from eulerpi.examples.heat import Heat

example_param = np.array([1.4, 1.6, 0.5])

sim_result = Heat().forward(example_param)
print(sim_result)

sim_result = Heat(example_param)
print(sim_result)
```

**Expected behavior**
The two variables sim_result should be identical, but they are not.

@Lars, is this some jax-related issue?

**Comment by kaiserls** [comment]
```python
import numpy as np
from eulerpi.examples.heat import Heat
example_param = np.array([1.4, 1.6, 0.5])

sim_result = Heat().forward(example_param)
print(sim_result) # Gives the correct simulation result

sim_result = Heat(example_param)
print(sim_result) # prints out the created object of the heat class

heat = Heat()
sim_result =heat(example_param) #throws a type error - `'Heat' object is not callable`
```
It seems like the feature was removed at some point, but the documentation is not updated.
I would simply update the documentation because it's always better to provide exactly one way to do one thing.
